# Generated by Django 5.0 on 2023-12-12 13:51

import django.db.models.deletion
# import gdstorage.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AI', 'الذكاء الاصطناعي'), ('ML', 'تعلم الآلة'), ('Bio', 'الأحياء'), ('Chem', 'الكيمياء'), ('Phys', 'الفيزياء'), ('Env', 'البيئة'), ('Math', 'الرياضيات'), ('Astro', 'الفلك'), ('Eng', 'الهندسة'), ('Med', 'الطب'), ('Neuro', 'علم الأعصاب'), ('Geo', 'علم الأرض'), ('Anthro', 'الأنثروبولوجيا'), ('Psy', 'علم النفس'), ('Socio', 'علم الاجتماع')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.category')),
            ],
        ),
    ]
