# Generated by Django 5.0 on 2023-12-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='external_doi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.CharField(default='الكلمة الدالة ', max_length=200),
            preserve_default=False,
        ),
    ]
