# Generated by Django 5.0 on 2023-12-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_reviewer_post_reviewer_comments_post_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
