# Generated by Django 5.0 on 2023-12-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_maincategory_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordtranslation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maincategory'),
        ),
    ]
