# Generated by Django 5.0 on 2023-12-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_keywordtranslation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_translation',
            field=models.BooleanField(default=False),
        ),
    ]
