# Generated by Django 5.0 on 2023-12-31 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_post_is_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.post')),
                ('translator', models.CharField(max_length=400)),
            ],
            bases=('main.post',),
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_translation',
        ),
    ]
