# Generated by Django 5.0 on 2024-01-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='english_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
