# Generated by Django 5.2.4 on 2025-07-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
    ]
