# Generated by Django 5.2.4 on 2025-07-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_post_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pdf',
            field=models.FileField(default=1, upload_to='pdfs'),
            preserve_default=False,
        ),
    ]
