# Generated by Django 5.2.4 on 2025-07-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_reviewerrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'تصنيف فرعي', 'verbose_name_plural': 'التصنيفات الفرعية'},
        ),
        migrations.AlterModelOptions(
            name='keywordtranslation',
            options={'verbose_name': 'ترجمة مصطلح', 'verbose_name_plural': 'ترجمات المصطلحات'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'التصنيف الرئيسي', 'verbose_name_plural': 'التصنيفات الرئيسية'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'مشاركة', 'verbose_name_plural': 'المشاركات'},
        ),
        migrations.AlterModelOptions(
            name='reviewerrequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'طلب مراجع', 'verbose_name_plural': 'طلبات المراجعين'},
        ),
        migrations.AlterModelOptions(
            name='translationpost',
            options={'verbose_name': 'مشاركة مترجمة', 'verbose_name_plural': 'المشاركات المترجمة'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'ملف المستخدم', 'verbose_name_plural': 'ملفات المستخدمين'},
        ),
    ]
