# Generated by Django 5.2.4 on 2025-07-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='admin_comments',
            field=models.TextField(blank=True),
        ),
    ]
