# Generated by Django 5.2.4 on 2025-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
