# Generated by Django 5.2.4 on 2025-07-31 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_comment_is_modified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='previous_reviewers',
            field=models.ManyToManyField(blank=True, help_text='Reviewers who have already reviewed this post', related_name='previously_reviewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
