# Generated by Django 5.2.4 on 2025-07-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_post_previous_reviewers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='الاسم')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('confirmation_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='مؤكد')),
            ],
            options={
                'verbose_name': 'مشترك في النشرة الإخبارية',
                'verbose_name_plural': 'المشتركون في النشرة الإخبارية',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
