# Generated by Django 5.2.4 on 2025-07-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_started',
            field=models.BooleanField(default=False, help_text='Indicates if the reviewer has started reviewing this post'),
        ),
    ]
