# Generated by Django 5.2.4 on 2025-07-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_add_review_started_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recommended_for_best_article',
            field=models.BooleanField(default=False, help_text='Indicates if the reviewer recommended this post for best article of the month'),
        ),
    ]
