# Generated by Django 5.2.4 on 2025-07-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_add_recommended_for_best_article_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='who_am_i',
            field=models.TextField(blank=True, help_text='ملخص مختصر عن الباحث', null=True, verbose_name='من أنا'),
        ),
    ]
