# Generated by Django 5.2.4 on 2025-08-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_add_who_am_i_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_edited_after_approval',
            field=models.BooleanField(default=False, help_text='Indicates if the post was edited after being approved'),
        ),
    ]
