# Generated by Django 5.2.4 on 2025-08-02 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_post_is_edited_after_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='final_reviewer',
            field=models.ForeignKey(blank=True, help_text='The reviewer who made the final decision (approved/rejected)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finally_reviewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
