# Generated by Django 5.2.4 on 2025-08-03 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_category_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleEmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='الاسم (اختياري)')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('confirmation_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='مؤكد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'اشتراك متعدد البريد الإلكتروني',
                'verbose_name_plural': 'الاشتراكات متعددة البريد الإلكتروني',
                'ordering': ['-subscribed_at'],
                'unique_together': {('user', 'email')},
            },
        ),
    ]
