# Generated by Django 5.2.4 on 2025-08-03 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_multipleemailsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleEmailSubscription',
        ),
    ]
