# Generated by Django 5.2.4 on 2025-08-03 01:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_multiple_email_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordtranslation',
            name='status',
            field=models.CharField(
                choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')],
                default='approved',
                max_length=20,
                verbose_name='الحالة'
            ),
        ),
        migrations.AddField(
            model_name='keywordtranslation',
            name='submitted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='auth.user',
                verbose_name='تم الإرسال بواسطة'
            ),
        ),
        migrations.AddField(
            model_name='keywordtranslation',
            name='submitted_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='تاريخ الإرسال'
            ),
        ),
        migrations.AlterModelOptions(
            name='keywordtranslation',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'ترجمة مصطلح', 'verbose_name_plural': 'ترجمات المصطلحات'},
        ),
    ]
