# Generated by Django 5.2.4 on 2025-08-04 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_add_status_to_keyword_translation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordtranslation',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال'),
        ),
        migrations.CreateModel(
            name='PostPdfView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_views', to='main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_pdf_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشاهدة PDF مشاركة',
                'verbose_name_plural': 'مشاهدات PDF المشاركات',
                'ordering': ['-viewed_at'],
                'unique_together': {('post', 'user')},
            },
        ),
    ]
