# Generated by Django 5.2.4 on 2025-08-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_keywordtranslation_submitted_at_postpdfview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='main.category', verbose_name='التصنيفات'),
        ),
    ]
