# Generated by Django 5.2.4 on 2025-08-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_post_category_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meaningful_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الرقم المعرفي'),
        ),
    ]
