# Generated by Django 5.2.4 on 2025-08-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_post_meaningful_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Approved', 'تمت الموافقة'), ('Rejected', 'مرفوض'), ('Rejected_For_Reassignment', 'مرفوض لإعادة التعيين')], default='Pending', max_length=30),
        ),
    ]
