# Generated by Django 5.2.4 on 2025-08-04 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_post_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the author in the paper (1 = first author)')),
                ('is_creator', models.BooleanField(default=False, help_text='Whether this user created the post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_authors', to='main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_posts_ordered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مؤلف مشاركة',
                'verbose_name_plural': 'مؤلفو المشاركات',
                'ordering': ['order'],
                'unique_together': {('post', 'user')},
            },
        ),
    ]
