# Generated by Django 5.2.4 on 2025-08-05 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_postauthor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('post', 'user')},
        ),
        migrations.AddField(
            model_name='postview',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session key for anonymous users', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='postview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('post', 'session_key'), ('post', 'user')},
        ),
        migrations.CreateModel(
            name='AnonymousPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_views', to='main.post')),
            ],
            options={
                'verbose_name': 'مشاهدة مجهولة',
                'verbose_name_plural': 'مشاهدات مجهولة',
                'ordering': ['-viewed_at'],
                'unique_together': {('post', 'session_key')},
            },
        ),
    ]
