# Generated by Django 5.2.4 on 2025-08-05 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_postview_unique_together_postview_session_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address for anonymous users', null=True),
        ),
        migrations.AddField(
            model_name='postview',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent for device identification', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('post', 'ip_address', 'user_agent'), ('post', 'user')},
        ),
        migrations.RemoveField(
            model_name='postview',
            name='session_key',
        ),
    ]
