# Generated by Django 5.2.4 on 2025-08-05 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_postview_unique_together_postview_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session key for anonymous users', max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('post', 'session_key'), ('post', 'user')},
        ),
        migrations.RemoveField(
            model_name='postview',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='postview',
            name='user_agent',
        ),
    ]
