# Generated by Django 5.2.4 on 2025-08-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_postview_unique_together_postview_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='confirmation_token',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='is_confirmed',
        ),
    ]
