"""
Django settings for arabicArxiv project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--(w5ln91oh)djklg6ap7i-d15y!dxk851gto^uyf^)(mvib@ul'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

MEDIA_URL = '/home/haadj/Arabarxiv/media/'
MEDIA_ROOT = MEDIA_URL
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "main.apps.MainConfig", 
    "crispy_forms", 
    "crispy_bootstrap5",
    'gdstorage', 
    'widget_tweaks'
]

GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE = '/home/haadj/Arabarxiv/arabarxiv-d287796b519e.json'
GOOGLE_DRIVE_STORAGE_KEY = "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"
GOOGLE_DRIVE_STORAGE_SERVICE_EMAIL = "haadjer.benmeziane@gmail.com"
GOOGLE_DRIVE_STORAGE_MEDIA_ROOT = 'https://drive.google.com/drive/folders/1vuHwP6JIAmsrS8ioifV3wNvwS7MSgEOu?usp=sharing'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'arabicArxiv.urls'
AUTH_PROFILE_MODULE = 'main.UserProfile'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'arabarxiv@gmail.com'
EMAIL_HOST_PASSWORD = 'juln nhlq tbyg xuev'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "main.context_processor.review_count_processor",
            ],
        },
    },
]

WSGI_APPLICATION = 'arabicArxiv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':"d3abgv2cvg8v4p", 
        "USER": "pexwfpuybglbxb", 
        "PASSWORD":"309b1344a44adfc80ccd4f1f7df601c7b71d7be8946d5c64b3c582f8465055a9", 
        "HOST":"ec2-54-73-22-169.eu-west-1.compute.amazonaws.com",
        "PORT":"5432"
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
# Specify the default country, if needed
COUNTRIES_DEFAULT = 'AE'

LANGUAGE_CODE = 'ar'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = "/home"
LOGOUT_REDIRECT_URL = '/logout'